# Generated by Django 4.1.7 on 2023-10-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpdf',
            name='pdf',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='BIO...', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='collection_statement',
            field=models.TextField(blank=True, default='Collection Statement...', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='collection_title',
            field=models.ImageField(blank=True, default='', null=True, upload_to='collection_title/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(blank=True, default='headshots/default_pp.jpg', null=True, upload_to='headshots/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_url',
            field=models.CharField(blank=True, default='www.instagram.com/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_url',
            field=models.CharField(blank=True, default='www.linkedin.com/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='David Mark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_intro',
            field=models.CharField(blank=True, default='Short Intro...', max_length=500, null=True),
        ),
    ]
